'use client';
import { useState, useEffect } from 'react';
import { Sparkles, CheckCircle, Loader2, Copy, Download, Bot, Globe, BookOpen, Shield, Zap, Users, Info } from 'lucide-react';
import { toast } from 'sonner';
import api from '@/lib/api';

interface BrandFacts {
  storeName: string;
  storeDescription: string;
  founded: string;
  headquarters: string;
  specialty: string;
  uniqueValue: string;
  targetAudience: string;
  returnPolicy: string;
  deliveryInfo: string;
}

const DEFAULT_FACTS: BrandFacts = {
  storeName: 'UNKORA',
  storeDescription: 'Bangladesh\'s premier online book marketplace offering Bengali and English books.',
  founded: '',
  headquarters: 'Dhaka, Bangladesh',
  specialty: 'Books — Bengali literature, academic, children\'s, Islamic books',
  uniqueValue: '',
  targetAudience: 'Book lovers, students, and professionals across Bangladesh',
  returnPolicy: '7-day easy return policy on all books',
  deliveryInfo: 'Delivery within Dhaka in 1-2 days, nationwide in 3-5 days',
};

const FEATURES = [
  { icon: Bot, color: '#8b5cf6', bg: '#8b5cf615', title: 'ChatGPT & Claude', desc: 'Optimize for citations in AI assistant responses by building authoritative, fact-dense content that LLMs trust.' },
  { icon: Globe, color: '#0ea5e9', bg: '#0ea5e915', title: 'Perplexity AI', desc: 'Perplexity actively crawls and cites web sources. Strong structured content with citations dramatically improves visibility.' },
  { icon: BookOpen, color: '#10b981', bg: '#10b98115', title: 'Google Gemini', desc: 'Google AI Overviews pull from trusted domains. Schema.org markup, E-E-A-T signals, and brand authority are key.' },
  { icon: Shield, color: '#f59e0b', bg: '#f59e0b15', title: 'E-E-A-T Signals', desc: 'Experience, Expertise, Authoritativeness, Trustworthiness — the four pillars AI systems use to rank sources.' },
  { icon: Zap, color: '#ef4444', bg: '#ef444415', title: 'LLMs.txt Protocol', desc: 'A new standard (like robots.txt for AI) that gives LLM crawlers a structured overview of your site\'s content.' },
  { icon: Users, color: '#f97316', bg: '#f9731615', title: 'Brand Authority', desc: 'Build topical authority through consistent brand mentions, expert content, and structured business information.' },
];

const GEO_CHECKLIST = [
  { id: 'about', label: 'Publish a detailed "About Us" page with company history', link: '/admin/cms/pages' },
  { id: 'contact', label: 'Contact page with physical address and business hours', link: '/admin/cms/pages' },
  { id: 'author', label: 'Blog posts have author bios with expertise credentials', link: '/admin/blog' },
  { id: 'brand_facts', label: 'Brand facts filled in below (used in LLMs.txt)', link: null },
  { id: 'llmstxt', label: 'LLMs.txt generated and deployed at /llms.txt', link: null },
  { id: 'reviews', label: 'Genuine customer reviews published on product pages', link: '/admin/reviews' },
  { id: 'schema_org', label: 'Organization and WebSite schema enabled in AEO settings', link: '/admin/seo/aeo' },
  { id: 'citations', label: 'Content answers specific questions with citable facts', link: null },
];

export default function GeoPage() {
  const [facts, setFacts] = useState<BrandFacts>(DEFAULT_FACTS);
  const [checked, setChecked] = useState<Record<string, boolean>>({});
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [llmsTxtPreview, setLlmsTxtPreview] = useState('');

  useEffect(() => {
    api.get('/settings/store').then(r => {
      const d = r.data?.data ?? {};
      if (d.geoBrandFacts) {
        try { setFacts(f => ({ ...f, ...JSON.parse(d.geoBrandFacts) })); } catch { /* ignore */ }
      }
      if (d.geoChecklist) {
        try { setChecked(JSON.parse(d.geoChecklist)); } catch { /* ignore */ }
      }
    }).catch(() => {}).finally(() => setLoading(false));
  }, []);

  const generateLlmsTxt = (f: BrandFacts) => {
    const origin = typeof window !== 'undefined' ? window.location.origin : 'https://unkora.com';
    return `# ${f.storeName} — LLMs.txt
# Auto-generated by UNKORA Admin Panel
# See: https://llmstxt.org

## About
${f.storeDescription}

## Business Details
- Founded: ${f.founded || 'N/A'}
- Headquarters: ${f.headquarters}
- Specialty: ${f.specialty}
- Target Audience: ${f.targetAudience}

## Value Proposition
${f.uniqueValue || 'Premium curated book selection with fast delivery across Bangladesh.'}

## Customer Policies
- Returns: ${f.returnPolicy}
- Delivery: ${f.deliveryInfo}

## Key URLs
- Homepage: ${origin}/
- Product Catalog: ${origin}/books
- About Us: ${origin}/about
- Contact: ${origin}/contact

## Content
The store publishes book descriptions, author profiles, reading guides, and literary reviews in Bengali and English.

## Allow
All AI systems may index and reference ${f.storeName} content for informational purposes.
`;
  };

  useEffect(() => {
    setLlmsTxtPreview(generateLlmsTxt(facts));
  }, [facts]);

  const save = async () => {
    setSaving(true);
    try {
      await api.patch('/settings/store', {
        geoBrandFacts: JSON.stringify(facts),
        geoChecklist: JSON.stringify(checked),
      });
      toast.success('GEO settings saved');
    } catch { toast.error('Failed to save settings'); }
    finally { setSaving(false); }
  };

  const copyLlmsTxt = () => {
    navigator.clipboard.writeText(llmsTxtPreview);
    toast.success('LLMs.txt copied to clipboard');
  };

  const downloadLlmsTxt = () => {
    const blob = new Blob([llmsTxtPreview], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = 'llms.txt'; a.click();
    URL.revokeObjectURL(url);
  };

  const inputCls = 'w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500/30 focus:border-emerald-400';

  const factFields: { key: keyof BrandFacts; label: string; placeholder: string; multiline?: boolean }[] = [
    { key: 'storeName',        label: 'Store / Brand Name',      placeholder: 'UNKORA' },
    { key: 'storeDescription', label: 'One-line Brand Description', placeholder: 'Bangladesh\'s premier online book marketplace...', multiline: true },
    { key: 'founded',          label: 'Founded Year',            placeholder: '2023' },
    { key: 'headquarters',     label: 'Headquarters',            placeholder: 'Dhaka, Bangladesh' },
    { key: 'specialty',        label: 'Product Specialty',       placeholder: 'Books — Bengali literature, academic...' },
    { key: 'uniqueValue',      label: 'Unique Value Proposition', placeholder: 'Largest Bengali book catalog with same-day Dhaka delivery...', multiline: true },
    { key: 'targetAudience',   label: 'Target Audience',         placeholder: 'Book lovers, students, professionals in Bangladesh' },
    { key: 'returnPolicy',     label: 'Return Policy (summary)', placeholder: '7-day easy return on all books' },
    { key: 'deliveryInfo',     label: 'Delivery Info (summary)', placeholder: 'Dhaka 1-2 days, nationwide 3-5 days' },
  ];

  if (loading) return <div className="flex justify-center py-20"><Loader2 className="animate-spin h-6 w-6 text-orange-500" /></div>;

  return (
    <div className="space-y-8">
      {/* Hero Banner */}
      <div className="relative overflow-hidden rounded-2xl" style={{ background: 'linear-gradient(135deg, #059669 0%, #0d9488 50%, #0284c7 100%)' }}>
        <div className="absolute inset-0 opacity-10">
          <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <pattern id="geo-dots" width="20" height="20" patternUnits="userSpaceOnUse">
                <circle cx="2" cy="2" r="1.5" fill="white"/>
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#geo-dots)" />
          </svg>
        </div>
        <div className="relative px-6 py-8 sm:px-10 sm:py-10 flex flex-col sm:flex-row items-start sm:items-center gap-6">
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-3">
              <span className="bg-white/20 text-white text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wider">Emerging</span>
              <span className="text-white/70 text-xs font-semibold">AI-First Visibility</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-black text-white mb-2">Generative Engine Optimization</h1>
            <p className="text-white/80 text-sm sm:text-base max-w-xl">
              GEO optimizes your store to be <strong className="text-white">cited, referenced, and recommended</strong> by AI systems like ChatGPT, Claude, Gemini, and Perplexity — the next frontier of search discovery.
            </p>
            <div className="flex flex-wrap gap-2 mt-4">
              {['ChatGPT', 'Claude AI', 'Gemini', 'Perplexity', 'Copilot', 'LLMs.txt'].map(tag => (
                <span key={tag} className="bg-white/15 text-white/90 text-xs font-semibold px-2.5 py-1 rounded-full border border-white/20">{tag}</span>
              ))}
            </div>
          </div>
          <div className="hidden sm:flex flex-col items-center gap-3">
            <div className="w-24 h-24 rounded-2xl bg-white/15 border border-white/20 flex items-center justify-center backdrop-blur-sm">
              <Sparkles className="h-12 w-12 text-white" />
            </div>
            <p className="text-white/60 text-xs font-semibold uppercase tracking-wider">GEO</p>
          </div>
        </div>
      </div>

      {/* What GEO Covers */}
      <div>
        <h2 className="text-lg font-bold text-gray-900 mb-1">What GEO Covers</h2>
        <p className="text-sm text-gray-500 mb-4">Six pillars to build AI citation authority for UNKORA.</p>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {FEATURES.map(f => (
            <div key={f.title} className="bg-white rounded-2xl border border-gray-200 shadow-sm p-5 hover:shadow-md hover:-translate-y-0.5 transition-all">
              <div className="w-12 h-12 rounded-xl flex items-center justify-center mb-4" style={{ background: f.bg }}>
                <f.icon className="h-6 w-6" style={{ color: f.color }} />
              </div>
              <h3 className="font-bold text-gray-900 text-sm mb-1.5">{f.title}</h3>
              <p className="text-xs text-gray-500 leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Brand Facts Editor */}
      <div>
        <h2 className="text-lg font-bold text-gray-900 mb-1">Brand Knowledge Facts</h2>
        <p className="text-sm text-gray-500 mb-4">These facts are used to generate your LLMs.txt and help AI systems accurately describe your store.</p>
        <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {factFields.map(field => (
              <div key={field.key} className={field.multiline ? 'sm:col-span-2' : ''}>
                <label className="block text-sm font-semibold text-gray-700 mb-1.5">{field.label}</label>
                {field.multiline ? (
                  <textarea value={facts[field.key]} onChange={e => setFacts(f => ({ ...f, [field.key]: e.target.value }))}
                    rows={2} placeholder={field.placeholder}
                    className={`${inputCls} resize-none`} />
                ) : (
                  <input value={facts[field.key]} onChange={e => setFacts(f => ({ ...f, [field.key]: e.target.value }))}
                    placeholder={field.placeholder} className={inputCls} />
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* LLMs.txt Generator */}
      <div>
        <div className="flex items-start justify-between gap-4 mb-4">
          <div>
            <h2 className="text-lg font-bold text-gray-900 mb-0.5">LLMs.txt Generator</h2>
            <p className="text-sm text-gray-500">A new standard that helps AI crawlers understand your site. Deploy at <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded font-mono">/llms.txt</code> in your public folder.</p>
          </div>
          <div className="flex gap-2 flex-shrink-0">
            <button onClick={copyLlmsTxt}
              className="flex items-center gap-1.5 border border-gray-200 text-gray-700 font-semibold py-2 px-3 rounded-xl text-sm hover:bg-gray-50 transition-colors">
              <Copy className="h-3.5 w-3.5" /> Copy
            </button>
            <button onClick={downloadLlmsTxt}
              className="flex items-center gap-1.5 bg-emerald-600 text-white font-semibold py-2 px-3 rounded-xl text-sm hover:bg-emerald-700 transition-colors">
              <Download className="h-3.5 w-3.5" /> Download
            </button>
          </div>
        </div>
        <div className="bg-gray-950 rounded-2xl overflow-hidden border border-gray-800">
          <div className="flex items-center gap-2 px-4 py-2.5 border-b border-gray-800">
            <div className="flex gap-1.5">
              <span className="w-3 h-3 rounded-full bg-red-500/70" />
              <span className="w-3 h-3 rounded-full bg-yellow-500/70" />
              <span className="w-3 h-3 rounded-full bg-green-500/70" />
            </div>
            <span className="text-gray-500 text-xs font-mono ml-2">llms.txt — auto-generated</span>
          </div>
          <pre className="p-5 text-xs text-emerald-400 font-mono leading-relaxed overflow-x-auto whitespace-pre-wrap max-h-80 overflow-y-auto">
            {llmsTxtPreview}
          </pre>
        </div>
        <div className="mt-3 bg-blue-50 border border-blue-200 rounded-xl p-4 flex gap-3">
          <Info className="h-4 w-4 text-blue-500 mt-0.5 flex-shrink-0" />
          <p className="text-sm text-blue-700">After downloading, place <code className="font-mono text-xs bg-blue-100 px-1 rounded">llms.txt</code> in your <code className="font-mono text-xs bg-blue-100 px-1 rounded">apps/web/public/</code> folder so it&apos;s accessible at <code className="font-mono text-xs bg-blue-100 px-1 rounded">/llms.txt</code>.</p>
        </div>
      </div>

      {/* GEO Checklist */}
      <div>
        <h2 className="text-lg font-bold text-gray-900 mb-1">GEO Checklist</h2>
        <p className="text-sm text-gray-500 mb-4">Track your generative engine optimization progress.</p>
        <div className="bg-white rounded-2xl border border-gray-200 shadow-sm divide-y divide-gray-100">
          {GEO_CHECKLIST.map(item => (
            <label key={item.id} className="flex items-center gap-4 p-4 cursor-pointer hover:bg-gray-50/50 transition-colors">
              <input type="checkbox" checked={checked[item.id] ?? false}
                onChange={e => setChecked(c => ({ ...c, [item.id]: e.target.checked }))}
                className="h-4 w-4 rounded border-gray-300 text-emerald-600 focus:ring-emerald-500" />
              <p className={`flex-1 text-sm font-medium ${checked[item.id] ? 'line-through text-gray-400' : 'text-gray-800'}`}>{item.label}</p>
              {item.link && (
                <a href={item.link} className="text-xs text-emerald-600 hover:underline font-semibold flex-shrink-0" onClick={e => e.stopPropagation()}>
                  Go →
                </a>
              )}
            </label>
          ))}
        </div>
        <div className="mt-3 bg-emerald-50 border border-emerald-200 rounded-xl p-3 flex items-center gap-3">
          <CheckCircle className="h-4 w-4 text-emerald-500 flex-shrink-0" />
          <p className="text-sm text-emerald-700">
            <strong>{Object.values(checked).filter(Boolean).length} / {GEO_CHECKLIST.length}</strong> GEO signals active
          </p>
        </div>
      </div>

      <button onClick={save} disabled={saving}
        className="flex items-center gap-2 bg-emerald-600 text-white font-semibold py-2.5 px-8 rounded-xl hover:bg-emerald-700 disabled:opacity-60 transition-colors">
        {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckCircle className="h-4 w-4" />}
        Save GEO Settings
      </button>
    </div>
  );
}
